### ISSUE TITLE
Have you some Binance examples?

### ISSUE THREAD

**Issue by icemagno** [cassandre-tech/crypto-trading-bot-tutorial#11]
Hi,
Can you please show how can I use the bot in a Binance account?

**Comment by straumat** [comment]
Create your project with :
```
mvn archetype:generate \
-DarchetypeGroupId=tech.cassandre.trading.bot \
-DarchetypeArtifactId=cassandre-trading-bot-spring-boot-starter-basic-archetype \
-DarchetypeVersion=4.1.0
```
Add to your pom.xml the following dependency:
```
<dependency>
    <groupId>org.knowm.xchange</groupId>
    <artifactId>xchange-binance</artifactId>
    <version>5.0.6</version>
</dependency>
```

Then  you have to change the file `src/main/resources/application.properties`
and set your Binance API parameters : 
```
cassandre.trading.bot.exchange.name=org.knowm.xchange.binance.BinanceExchange
cassandre.trading.bot.exchange.username=username
cassandre.trading.bot.exchange.passphrase=yourpasshrase
cassandre.trading.bot.exchange.key=6054ad25365ac6000689a998
cassandre.trading.bot.exchange.secret=af080d55-afe3-47c9-8ec1-4b479fbcc5e7
```
It should work with that !

**Comment by AllirionX** [comment]
I believe binance does use username and passphrase, only the api key and secret. However the cassandre bot requires those two properties to not be empty.

**Comment by straumat** [comment]
@AllirionX just set binance to passphrase and put your account username in username

**Comment by icemagno** [comment]
@AllirionX you are correct. We only need a key and a secret that we take from the API configuration. 

I'm working on a spring boot web portal using the Binance java API wrapper from https://github.com/binance-exchange/binance-java-api

That is only what we need.

**Comment by icemagno** [comment]
@straumat I think this is a bit dangerous since the API keypair protect your account from ilegal operations

**Comment by straumat** [comment]
@icemagno yes but i think cassandre should still work if u set fake values in username and passphrase ?

**Comment by AllirionX** [comment]
@straumat Yes, fake values work, it's just not ideal that Cassandre requires some value to be set.

**Comment by straumat** [comment]
Yes indeed. I will work on it.
